"""Named French policy chapters. These are proposals within the authorized routes,
not claims that each policy or counterfactual event occurred historically."""


def chapter(key, title, route, anchor, domain, modifier, names, questions, dilemma):
    names = names.split('|')
    questions = questions.split('|')
    if len(names) != 15 or len(questions) != 3:
        raise ValueError(f'{key}: expected 15 focuses and 3 event topics')
    return dict(key=key,title=title,route=route,anchor=anchor,domain=domain,modifier=modifier,names=names,questions=questions,dilemma=dilemma)

CHAPTERS = [
chapter('assembly','The Nation Assembles','common','FRA_convene_estates_general','politics','political_power_factor = 0.03',
 'Hear the Cahiers|A National Mandate|Respect the Local Delegations|Verify the Common Mandate|Preserve Provincial Channels|The Question of Representation|Open the Public Galleries|Protect the Petitioners|Publish the Proceedings|Establish Rules of Debate|The Delegates Seek an Answer|Finance a Permanent Secretariat|Keep a Rotating Secretariat|Record the Settlement|An Administration Answerable to France',
 'Petitions Reach the Government|Who Speaks for the Departments?|Paying for Representation',
 'Delegates want their petitions translated into durable institutions. A centralized settlement is efficient, but local participation may give it greater legitimacy.'),
chapter('credit','The State Ledger','common','FRA_convene_estates_general','finance','political_power_factor = 0.03',
 'Open the Treasury Books|Guarantee the Public Debt|Renegotiate the Old Obligations|Consolidate the Loan Register|Agree a Voluntary Rescheduling|Creditors Seek Security|Audit the Tax Farms|Survey National Assets|Recover Missing Receipts|Publish the Budget|Paper Promises and Real Revenue|Create a Permanent Debt Office|Retain Provincial Collection|Protect the Revenue Base|A Credible State Ledger',
 'The Creditors Demand Security|The Assignat Question|Who Bears the Fiscal Settlement?',
 'The treasury cannot solve every obligation by issuing another promise. Credit, taxation and confidence must be rebuilt together, with visible costs for each alternative.'),
chapter('departments','Governing the Provinces','common','FRA_convene_estates_general','administration','stability_factor = 0.03',
 'Survey the Provinces|Appoint National Commissioners|Work Through Municipal Councils|Standardize Administrative Returns|Protect Local Expertise|Privileges Meet Administration|Register Public Land|Inspect Roads and Bridges|Train the Clerks|Improve the Postal Routes|Who Selects the Officials?|Professionalize the Prefectures|Guarantee Municipal Deliberation|Reconcile the Civil Registers|A State Beyond the Capital',
 'Provincial Privileges|The Appointment of Officials|The Civil Register',
 'The centre needs reliable information and revenue; communities need officials who understand local conditions. Administrative reach is not the same as public consent.'),
chapter('learning','Knowledge and Public Service','common','FRA_convene_estates_general','science','research_speed_factor = 0.025',
 'Inventory the Schools|Sponsor National Academies|Support Municipal Schools|Train Scientific Administrators|Preserve Local Teaching Networks|Who Controls Education?|Survey Weights and Measures|Publish Practical Manuals|Educate Military Engineers|Open the Public Archives|The Metric Proposal|Endow a National Institute|Prioritize Technical Workshops|Examine the New Civil Servants|Knowledge in the Service of the State',
 'Education and Authority|A Common System of Measures|An Academy for Public Service',
 'Education, measurement and practical science can improve state capacity. Funding national institutions competes with support for the workshops and schools already serving local communities.'),
chapter('infantry','Infantry Institutions','common','FRA_convene_estates_general','infantry','army_org_factor = 0.025',
 'Inspect the Infantry Regiments|Emphasize Disciplined Volleys|Encourage Aimed Skirmishing|Standardize Volley Commands|Train the Light Companies|Veterans and New Recruits|Improve the Battalion Schools|Record Regimental Experience|Build a Reliable NCO Corps|Inspect Small-Arms Maintenance|Integrating the Volunteers|Favor Large Training Camps|Disperse the Training Cadres|Evaluate the Regimental System|A Cohesive Infantry Arm',
 'The Veterans and the Recruits|The Volunteer Battalions|Discipline Without Blindness',
 'The infantry needs both cohesion and initiative. Drill, competent junior leaders and the integration of recruits matter more than assuming that enthusiasm alone will win a campaign.'),
chapter('cavalry','The Mounted Arm','common','FRA_convene_estates_general','cavalry','army_speed_factor = 0.025',
 'Survey the Remount Depots|Prioritize the Heavy Horse|Prioritize the Light Horse|Strengthen the Shock Squadrons|Expand the Reconnaissance Patrols|A Shortage of Remounts|Improve Veterinary Care|Standardize Cavalry Saddles|Drill Dismounted Action|Coordinate the Screening Force|Choosing the Cavalry Balance|Concentrate the Cavalry Reserve|Distribute Mounted Scouts|Rehearse the Pursuit|A Sustainable Mounted Arm',
 'The Remount Shortage|Hussars or Heavy Horse?|Screening the March',
 'Cavalry is costly to maintain and difficult to replace. A powerful reserve cannot substitute for screening, reconnaissance and a functioning supply of healthy horses.'),
chapter('guns','Guns and Magazines','common','FRA_convene_estates_general','artillery','army_attack_factor = 0.025 supply_consumption_factor = 0.015',
 'Inspect the Artillery Parks|Concentrate the Heavy Batteries|Favor Mobile Field Batteries|Organize the Siege Trains|Improve Horse-Artillery Drill|The Guns or the Roads?|Standardize Ammunition Returns|Inspect the Powder Mills|Train the Battery Officers|Fund the Wagon Depots|The Ammunition Contracts|Create a Central Artillery Reserve|Attach Guns to the Formations|Rehearse Combined Fire Plans|An Artillery System That Can Move',
 'The Guns or the Roads?|The Ammunition Contracts|Commanding the Artillery Reserve',
 'Additional guns are useful only if ammunition, teams and roads can sustain them. Firepower and mobility compete for the same limited resources.'),
chapter('fleet','Rebuilding the Fleet','common','FRA_convene_estates_general','navy','navy_org_factor = 0.04',
 'Review the Naval Establishment|Concentrate the Battle Fleet|Protect the Merchant Convoys|Rehearse Line-of-Battle Signals|Organize Coastal Escort Stations|Officers and Political Trust|Inspect the Dockyards|Survey the Naval Stores|Train the Petty Officers|Maintain the Channel Ports|Convoys or the Battle Line?|Build a Strategic Naval Reserve|Disperse the Cruising Squadrons|Reconcile the Naval Accounts|A Fleet with a Sustainable Purpose',
 'Officers at Sea|Convoys or the Battle Fleet?|Replacing Lost Ships',
 'The navy must choose between concentrated battle power, commerce protection and dispersed operations. Hulls, crews, dockyards and experienced officers cannot be replaced instantly.'),
chapter('charter','A Constitutional Crown','constitutional','FRA_constitutional_monarchy','politics','political_power_factor = 0.03 stability_factor = 0.02',
 'Define the Crown in Law|A Suspensive Royal Veto|A Narrower Executive Veto|Specify the Ministers Powers|Protect Legislative Independence|The Royal Veto Debate|Publish the Civil List|Guarantee Personal Security|An Oath to the Constitution|Limit Emergency Ordinances|The Crown Faces the Charter|Seek a Broad Constitutional Compact|Entrench Detailed Legal Safeguards|Create a Constitutional Review Procedure|A Crown Bound by Law',
 'The Royal Veto|An Oath to the Charter|The Crown and the Assembly',
 'A constitutional settlement needs rules that survive disagreement. The crown, ministers and representatives must know which powers they possess and where those powers end.'),
chapter('representation','Representative Government','constitutional','FRA_constitutional_monarchy','administration','stability_factor = 0.04 war_support_factor = -0.02',
 'Establish Electoral Registers|A Property-Based Franchise|Broaden Civic Participation|Protect Independent Electors|Extend Municipal Representation|Who Elects the Deputies?|Publish Ministerial Accounts|Allow Organized Parliamentary Debate|Establish Budget Committees|Protect Opposition Petitions|Responsibility for the Cabinet|A Stable Ministerial Programme|Frequent Legislative Scrutiny|Define Confidence and Resignation|An Accountable Constitutional Government',
 'The Electoral Settlement|Cabinet Responsibility|Public Finance Under Scrutiny',
 'Representative government requires more than periodic voting. Electoral rules, responsible ministers and scrutiny of public expenditure determine whether opposition remains inside the political system.'),
chapter('constitutional_diplomacy','Constitutional Diplomacy','constitutional','FRA_constitutional_europe','diplomacy','trade_opinion_factor = 0.15',
 'A Foreign Policy for the Charter|Reassure the Established Courts|Reach Out to Reforming States|Guarantee Existing Treaties|Exchange Constitutional Delegations|Reform Without Exporting War|Protect Neutral Commerce|Regularize Diplomatic Instructions|Professionalize the Consular Service|Publish Limited War Aims|Neutral Trading Partners|Favor Defensive Understandings|Favor Bilateral Settlements|Review the Security Commitments|A Constitutional Place in Europe',
 'Reform Without Exporting War|Neutral Trading Partners|A Mutual Security Charter',
 'Constitutional France can defend its settlement without imposing it abroad. Diplomatic commitments must be credible, limited and compatible with the government established at home.'),
chapter('court','Rebuilding Royal Authority','royalist','FRA_restore_ancien_regime','royal','political_power_factor = 0.05',
 'Reconstitute the Royal Council|Reward Proven Service|Reconcile Former Opponents|Audit Court Appointments|Offer Conditional Pardons|The Price of Loyalty|Restore Provincial Correspondence|Publish the Royal Budget|Secure the Civil Courts|Clarify the Officers Oaths|Reconcile the Provinces|Rule Through a Compact Council|Restore Consultation with the Estates|Inspect the Royal Administration|A Crown Capable of Governing',
 'The Price of Loyalty|Reconciliation in the Provinces|A Crown That Can Govern',
 'The restoration of royal authority creates a choice between rewarding loyal supporters and reconciling a divided country. Patronage without administration will not produce durable stability.'),
chapter('emigres','The Emigre Return','royalist','FRA_emigre_army','military','army_org_factor = 0.03',
 'Register the Returning Officers|Restore Experienced Commissions|Examine Every Commission|Rebuild the Veteran Cadres|Require Professional Examinations|Returning Officers Meet the Army|Regularize Emigre Pensions|Inspect Overseas Service Records|Settle Disputed Property Claims|Unify Regimental Pay|Property and Amnesty|Keep the Old Regimental Traditions|Create a Common Service Code|Enforce One Chain of Command|An Army Reconciled to the Crown',
 'The Returning Officers|Property and Amnesty|One Chain of Command',
 'Returning officers bring experience but also grievances and rival claims to rank. The army must become a single institution rather than an alliance of competing patrons.'),
chapter('royal_order','The Monarchical Settlement','royalist','FRA_european_concert','diplomacy','stability_factor = 0.03 political_power_factor = 0.02',
 'State the Royal Peace Programme|Seek Dynastic Guarantees|Seek Limited Defensive Treaties|Renew the Courtly Channels|Clarify the Limits of Assistance|The Courts Consider France|Reconcile Ecclesiastical Administration|Review Seized Endowments|Protect Civil Contracts|Codify Provincial Obligations|The Religious Settlement|Preserve Traditional Councils|Professionalize the Royal Ministries|Publish a Durable Legal Settlement|A Monarchy within the European Order',
 'The Courts of Europe|The Religious Settlement|Councils and Law',
 'A restored monarchy needs a diplomatic and legal settlement that can survive the immediate crisis. Support from foreign courts cannot replace a workable domestic government.'),
chapter('convention','The National Convention','republican','FRA_vive_la_republique','republic','war_support_factor = 0.04',
 'Organize the Convention Committees|Concentrate Executive Supervision|Strengthen Departmental Oversight|Define Emergency Mandates|Protect Local Reporting Rights|Mandates from the Departments|Regularize Army Requisitions|Publish the Republican Budget|Audit the War Ministries|Safeguard Civil Administration|War and Representation|A Unified Executive Committee|A Balance of Representative Committees|Review Emergency Authority|The Institutions of the Citizen State',
 'Mandates from the Departments|War and Representation|The Citizen State',
 'The republic faces the problem of governing during war without allowing emergency powers to become an unaccountable substitute for representative institutions.'),
chapter('girondins','A Provincial Republic','republican','FRA_vive_la_republique','republic','political_power_factor = 0.04 stability_factor = 0.025',
 'A Girondin Programme|Defend Departmental Autonomy|Build a National Parliamentary Majority|Strengthen Municipal Accountability|Negotiate a Legislative Compact|Paris and the Provinces|Protect Petition and Association|Limit Extraordinary Tribunals|Publish the Detention Registers|Separate Civil and Military Authority|Liberty Under Pressure|Seek a Broad Republican Coalition|Entrench a Legal Opposition|Prepare a Post-Emergency Constitution|A Republic without Permanent Terror',
 'Paris and the Provinces|Liberty Under Pressure|A Republic without the Terror',
 'The moderate republican programme seeks national cooperation without unlimited central coercion. Its success depends on obtaining resources and military coordination through institutions that retain public consent.'),
chapter('jacobins','The Jacobin Programme','republican','FRA_vive_la_republique','republic','war_support_factor = 0.05 stability_factor = -0.03',
 'A Jacobin Programme|Centralize the Emergency Mandate|Anchor Policy in the Sections|Coordinate the Committees|Organize Local Supply Reports|Mandates for Emergency Powers|Inspect the Army Contractors|Expand Relief to Soldiers Families|Supervise Grain Deliveries|Define the Representatives Powers|Relief and Revolutionary Authority|Prioritize a Unified War Executive|Prioritize Civilian Relief|Review Exceptional Powers|The Republic under a Central Mandate',
 'Mandates for Emergency Powers|Relief to the Sections|The Limits of Central Power',
 'The radical programme connects emergency government with mobilization and public relief. Concentrated authority can deliver resources quickly but carries political and institutional costs.'),
chapter('emergency','The Republic at War','republican','FRA_levee_en_masse_focus','military','army_org_factor = 0.025 war_support_factor = 0.03',
 'Coordinate the War Effort|Prioritize the Front-Line Armies|Prioritize the Home Departments|Standardize Field Supply Returns|Improve Internal Communications|The Committee and the Army|Survey Internal Unrest|Protect the Grain Routes|Establish Local Mediation Channels|Regularize Emergency Levies|The Vendee Crisis|Fund Sustained Military Administration|Fund Civil Relief and Reconstruction|Prepare the Return to Ordinary Law|A Republic Able to Demobilize',
 'The Committee and the War Effort|The Vendee Crisis|Bread and Mobilization',
 'External war and internal unrest compete for men, supplies and attention. Durable recovery needs lawful administration, reliable food supplies and a route back from emergency government.'),
chapter('directory','The Directory Settlement','directory','FRA_vive_la_republique','administration','political_power_factor = 0.03 research_speed_factor = 0.02',
 'Review the Executive Directory|Stabilize the Executive Councils|Broaden the Parliamentary Settlement|Regularize Ministerial Appointments|Secure Departmental Cooperation|A Constitution for Recovery|Audit the Army Contracts|Investigate Fiscal Patronage|Restore Municipal Credit|Publish Electoral Procedures|Pressure on the Elections|Strengthen Civilian Supervision|Negotiate with the Military Leadership|Set Limits on Emergency Intervention|An Executive That Can Survive Peace',
 'A Constitution for Recovery|Electoral Pressure|The Army and Civil Government',
 'The Directory must prevent military success, fiscal patronage and political instability from consuming civilian government. Efficiency alone cannot guarantee legitimacy.'),
chapter('italy','The Army of Italy','campaign','FRA_italian_campaign','military','planning_speed = 0.04',
 'Assess the Army of Italy|Prioritize a Concentrated Advance|Prepare a Cautious Supply Programme|Coordinate the Mountain Columns|Repair the Forward Magazines|The Unpaid Army of Italy|Train Mountain Reconnaissance|Coordinate Artillery on Narrow Roads|Pay the Local Suppliers|Clarify the Commanders Authority|Separate Peace or Continued Pursuit|Seek a Limited Diplomatic Settlement|Prepare a Sustained Italian Presence|Inspect the Occupation Accounts|A Campaign with Political Objectives',
 'The Unpaid Army of Italy|Separate Peace or Pursuit?|The Italian Settlement',
 'The Italian campaign joins operational opportunity to a fragile supply situation. Agreements with local authorities and clear political objectives matter as much as battlefield success.'),
chapter('egypt','The Eastern Expedition','campaign','FRA_egyptian_expedition','navy','supply_consumption_factor = -0.025',
 'Review the Eastern Expedition|Prioritize Naval Protection|Prioritize the Land Establishment|Prepare the Escort Squadrons|Stock the Expeditionary Depots|The Fleet and the Expedition|Train Interpreters and Surveyors|Organize Medical Stores|Establish Reliable Courier Routes|Inspect the Expedition Accounts|Scholars and Soldiers|Preserve the Expeditionary Establishment|Prepare an Orderly Withdrawal|Protect the Returning Cadres|Lessons from the Eastern Expedition',
 'The Fleet and the Expedition|Scholars and Soldiers|Returning from the East',
 'A distant expedition cannot assume secure communications or unlimited local resources. Its scientific ambitions, military objectives and prospects for withdrawal must be reconciled.'),
chapter('consulate','The Consular State','consular','FRA_brumaire_coup','administration','industrial_capacity_factory = 0.025',
 'Organize the Consular Administration|A Concentrated Executive|A Wider Consultative Settlement|Coordinate the Ministries|Regularize Legislative Consultation|Power and Ratification|Consolidate State Credit|Review the Civil Law Drafts|Reorganize the Tax Offices|Protect Administrative Continuity|Banking and the Civil Code|A Uniform Administrative Hierarchy|A Negotiated Provincial Settlement|Review the Consular Institutions|A State beyond the Coup',
 'Power and Ratification|Banking and the Civil Code|The Consular Settlement',
 'The coup has created an executive, not yet a durable state. Credit, law, administration and public acceptance must turn military authority into workable government.'),
chapter('empire','Administering the Empire','imperial','FRA_proclaim_empire','administration','political_power_factor = 0.04',
 'Survey the Imperial Administration|Strengthen the Prefects|Rely on Established Local Elites|Inspect Departmental Performance|Negotiate Local Cooperation|Prefects and Notables|Publish Imperial Revenue Estimates|Coordinate Conscription Registers|Inspect the Main Post Roads|Professionalize Ministerial Reporting|The Taxpayer and the Conscript|Centralize the Imperial Accounts|Permit Provincial Adaptation|Audit the Costs of Expansion|An Empire That Can Administer Itself',
 'Prefects and Notables|The Taxpayer and the Conscript|Administering a Larger State',
 'Imperial expansion creates obligations as well as resources. Central direction must be reconciled with the capacity of provincial administration and the burdens placed on households.'),
chapter('marshals','Marshals and Corps','imperial','FRA_grande_armee_focus','military','max_planning_factor = 0.04',
 'Review the Marshalate|Promote Demonstrated Merit|Balance Seniority and Loyalty|Inspect Independent Commands|Regularize the Service Records|Merit and Seniority|Establish Corps Staff Standards|Coordinate March Tables|Improve Liaison between Corps|Train Reserve Staff Officers|Independent Corps in One Campaign|Grant Operational Initiative|Emphasize Detailed Central Orders|Rehearse the Concentration Plan|A Grande Armee of Coordinated Corps',
 'Merit or Seniority?|Independent Corps|Honour and Command',
 'A corps system needs commanders who can act independently without losing sight of the wider campaign. Prestige, loyalty and professional competence do not always point to the same appointments.'),
chapter('clients','The Client-State Network','imperial','FRA_confederation_rhine','diplomacy','trade_opinion_factor = 0.15',
 'Survey the Allied Administrations|Favor Local Constitutional Partners|Favor Close Administrative Direction|Negotiate Local Contributions|Inspect the Dependent Ministries|Republics or Dependencies?|Regularize Military Access|Coordinate Allied Supply Accounts|Review Local Officer Commissions|Publish Treaty Obligations|The Local Elites Seek Guarantees|Fund Durable Client Institutions|Limit the Burden of Military Contributions|Audit the Cost of the Network|Clients with Defined Rights and Duties',
 'Republics or Dependencies?|The Local Elites|The Cost of Allied Armies',
 'Allied and dependent states need defined obligations and a reason to cooperate. Their administration cannot be treated as an unlimited source of money and soldiers.'),
chapter('continental','The Continental System','imperial','FRA_continental_system_focus','finance','industrial_capacity_factory = 0.025 trade_opinion_factor = -0.05',
 'Survey the Continental Ports|Enforce Uniform Commercial Rules|Permit Negotiated Exceptions|Coordinate Customs Reporting|Protect Essential Imports|Ports under Pressure|Inspect the Customs Services|Protect Domestic Credit|Review Industrial Bottlenecks|Audit the Port Administrations|Smuggling and Exceptions|Fund a Sustained Customs Establishment|Relax Rules That Cannot Be Enforced|Review the Costs of the Blockade|An Economic Strategy with Limits',
 'Ports under Pressure|Smuggling and Exceptions|The Cost of Economic War',
 'Economic warfare redistributes losses across merchants, manufacturers, allies and consumers. A decree that cannot be enforced can weaken the very coalition of interests needed to sustain it.'),
chapter('peninsula','The Peninsular Commitment','imperial','FRA_invade_iberia','military','supply_consumption_factor = -0.03',
 'Assess the Iberian Commitment|Concentrate the Main Field Army|Protect Communications First|Coordinate the Operational Columns|Strengthen the Supply Garrisons|Roads without Security|Inspect Local Supply Agreements|Regularize Civilian Compensation|Review the Intelligence Reports|Secure the Courier Network|The Question of Local Authority|Fund a Sustained Military Presence|Prepare a Limited Political Settlement|Measure the True Cost of the Campaign|A Strategy for the Peninsula',
 'Roads without Security|The Question of Local Authority|Subsidizing the Campaign',
 'An army can win field engagements while losing control of its communications and political position. The campaign needs reliable supplies and a viable relationship with local society.'),
chapter('russia','Distance and Recovery','late_imperial','FRA_invade_russia','military','supply_consumption_factor = -0.04',
 'Estimate the Eastern Distances|Prioritize a Rapid Concentration|Prepare for a Prolonged Campaign|Coordinate the Forward Echelons|Build Redundant Supply Plans|Preparing for Distance|Record the Condition of the Army|Preserve the Experienced Cadres|Survey the Remaining Magazines|Plan an Orderly Withdrawal|The Costs of Retreat|Rebuild around Veteran Formations|Prioritize Civil and Military Recovery|Review the Political Settlement|A State Capable of Surviving Defeat',
 'Preparing for Distance|The Costs of Retreat|Rebuilding after Defeat',
 'A long campaign tests the entire military and political system. Preserving cadres, protecting communications and organizing recovery may become more important than pursuing another distant objective.')
]
